name: agenda
description: "Une application permettant de garder un historique des evenements passé, ainsi que de ceux a venir"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  timezone: ^0.10.1
  flutter_local_notifications: ^19.1.0
  external_path: ^2.2.0
  file_picker: ^10.1.2
  permission_handler: ^12.0.0+1
  scrollable_positioned_list: ^0.3.8
  intl: ^0.18.0
  path_provider: ^2.0.10
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/logo.png"

flutter:
  uses-material-design: true
  assets:
  - assets/icons/
